// login
export const FORM_LOGIN_ACTION_REQUEST = 'FORM_LOGIN_ACTION_REQUEST'
export const FORM_LOGIN_ACTION_ERROR = 'FORM_LOGIN_ACTION_ERROR'
export const FORM_LOGIN_ACTION_SUCCESS = 'FORM_LOGIN_ACTION_SUCCESS'

// update user
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR'

export const USER_UPDATE_PROFILE_PIC = 'USER_UPDATE_PROFILE_PIC'
export const USER_UPDATE_PROFILE_PIC_SUCESS = 'USER_UPDATE_PROFILE_PIC_SUCCESS'


// persist
export const PERSIST_REHYDRATE = 'persist/REHYDRATE'
